"""
Common stock ticker → canonical symbol lookup.
Keys are lowercase name variants (full names, common nicknames, abbreviations).
Used to resolve company names spoken/typed by users into ticker symbols.
"""
import re

# name (lowercase) → ticker
COMPANY_NAME_TO_TICKER: dict[str, str] = {
    # ── Mega-cap Tech ──────────────────────────────────────────────────────────
    "apple": "AAPL",
    "microsoft": "MSFT",
    "nvidia": "NVDA",
    "nvda": "NVDA",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "meta": "META",
    "facebook": "META",
    "amazon": "AMZN",
    "tesla": "TSLA",
    "broadcom": "AVGO",
    "oracle": "ORCL",
    "salesforce": "CRM",
    "adobe": "ADBE",
    "intel": "INTC",
    "amd": "AMD",
    "advanced micro devices": "AMD",
    "qualcomm": "QCOM",
    "texas instruments": "TXN",
    "applied materials": "AMAT",
    "lam research": "LRCX",
    "kla": "KLAC",
    "micron": "MU",
    "micron technology": "MU",
    "western digital": "WDC",
    "seagate": "STX",
    "corning": "GLW",
    "motorola": "MSI",
    "motorola solutions": "MSI",
    "juniper": "JNPR",
    "juniper networks": "JNPR",
    "arista": "ANET",
    "arista networks": "ANET",
    "palo alto": "PANW",
    "palo alto networks": "PANW",
    "crowdstrike": "CRWD",
    "fortinet": "FTNT",
    "zscaler": "ZS",
    "cloudflare": "NET",
    "datadog": "DDOG",
    "snowflake": "SNOW",
    "mongodb": "MDB",
    "elastic": "ESTC",
    "palantir": "PLTR",
    "servicenow": "NOW",
    "workday": "WDAY",
    "veeva": "VEEV",
    "hubspot": "HUBS",
    "zendesk": "ZEN",
    "twilio": "TWLO",
    "docusign": "DOCU",
    "zoom": "ZM",
    "zoom video": "ZM",
    "dropbox": "DBX",
    "box": "BOX",
    "shopify": "SHOP",
    "squarespace": "SQSP",
    "wix": "WIX",
    "godaddy": "GDDY",
    "roblox": "RBLX",
    "unity": "U",
    "unity software": "U",
    "take-two": "TTWO",
    "take two": "TTWO",
    "activision": "ATVI",
    "electronic arts": "EA",
    "ea": "EA",
    "ubisoft": "UBSFY",
    "netflix": "NFLX",
    "spotify": "SPOT",
    "airbnb": "ABNB",
    "uber": "UBER",
    "lyft": "LYFT",
    "doordash": "DASH",
    "instacart": "CART",
    "pinterest": "PINS",
    "snap": "SNAP",
    "snapchat": "SNAP",
    "twitter": "TWTR",
    "x": "TWTR",
    "reddit": "RDDT",
    "linkedin": "MSFT",
    "ebay": "EBAY",
    "etsy": "ETSY",
    "wayfair": "W",
    "chewy": "CHWY",
    "paypal": "PYPL",
    "square": "SQ",
    "block": "SQ",
    "stripe": "STRP",
    "visa": "V",
    "mastercard": "MA",
    "american express": "AXP",
    "amex": "AXP",
    "discover": "DFS",
    "coinbase": "COIN",
    "robinhood": "HOOD",
    "sofi": "SOFI",
    "affirm": "AFRM",
    "klarna": "KLAR",
    "intuit": "INTU",
    "turbotax": "INTU",
    "verisign": "VRSN",
    "godaddy": "GDDY",
    "akamai": "AKAM",
    "fastly": "FSLY",
    "ibm": "IBM",
    "hewlett packard": "HPQ",
    "hp": "HPQ",
    "hpe": "HPE",
    "dell": "DELL",
    "cisco": "CSCO",
    "sap": "SAP",
    "accenture": "ACN",
    "cognizant": "CTSH",
    "infosys": "INFY",
    "wipro": "WIT",

    # ── Financials ────────────────────────────────────────────────────────────
    "jpmorgan": "JPM",
    "jp morgan": "JPM",
    "chase": "JPM",
    "bank of america": "BAC",
    "wells fargo": "WFC",
    "goldman sachs": "GS",
    "morgan stanley": "MS",
    "citigroup": "C",
    "citi": "C",
    "us bancorp": "USB",
    "pnc": "PNC",
    "truist": "TFC",
    "capital one": "COF",
    "charles schwab": "SCHW",
    "schwab": "SCHW",
    "fidelity": "FNF",
    "blackrock": "BLK",
    "vanguard": "V",
    "state street": "STT",
    "invesco": "IVZ",
    "franklin templeton": "BEN",
    "t rowe price": "TROW",
    "raymond james": "RJF",
    "edward jones": "EDJ",
    "berkshire": "BRK.B",
    "berkshire hathaway": "BRK.B",
    "insurance": "MET",
    "aig": "AIG",
    "allstate": "ALL",
    "progressive": "PGR",
    "metlife": "MET",
    "prudential": "PRU",
    "hartford": "HIG",
    "travelers": "TRV",

    # ── Healthcare & Pharma ───────────────────────────────────────────────────
    "johnson and johnson": "JNJ",
    "johnson & johnson": "JNJ",
    "j&j": "JNJ",
    "pfizer": "PFE",
    "merck": "MRK",
    "abbvie": "ABBV",
    "eli lilly": "LLY",
    "lilly": "LLY",
    "bristol myers": "BMY",
    "bristol-myers squibb": "BMY",
    "amgen": "AMGN",
    "gilead": "GILD",
    "biogen": "BIIB",
    "regeneron": "REGN",
    "moderna": "MRNA",
    "biontech": "BNTX",
    "unitedhealth": "UNH",
    "united health": "UNH",
    "cvs": "CVS",
    "cigna": "CI",
    "humana": "HUM",
    "aetna": "CVS",
    "anthem": "ELV",
    "elevance": "ELV",
    "centene": "CNC",
    "molina": "MOH",
    "danaher": "DHR",
    "becton dickinson": "BDX",
    "bd": "BDX",
    "medtronic": "MDT",
    "stryker": "SYK",
    "boston scientific": "BSX",
    "edwards lifesciences": "EW",
    "intuitive surgical": "ISRG",
    "zimmer biomet": "ZBH",
    "hologic": "HOLX",
    "quest diagnostics": "DGX",
    "labcorp": "LH",
    "cardinal health": "CAH",
    "mckesson": "MCK",
    "thermo fisher": "TMO",
    "agilent": "A",
    "illumina": "ILMN",
    "10x genomics": "TXG",
    "crispr": "CRSP",
    "vertex": "VRTX",
    "alnylam": "ALNY",
    "bluebird bio": "BLUE",

    # ── Consumer / Retail ─────────────────────────────────────────────────────
    "walmart": "WMT",
    "target": "TGT",
    "costco": "COST",
    "home depot": "HD",
    "lowes": "LOW",
    "lowe's": "LOW",
    "dollar general": "DG",
    "dollar tree": "DLTR",
    "five below": "FIVE",
    "best buy": "BBY",
    "gamestop": "GME",
    "bed bath beyond": "BBBY",
    "macys": "M",
    "macy's": "M",
    "nordstrom": "JWN",
    "gap": "GPS",
    "nike": "NKE",
    "adidas": "ADDYY",
    "under armour": "UA",
    "lululemon": "LULU",
    "tapestry": "TPR",
    "ralph lauren": "RL",
    "pvh": "PVH",
    "hanesbrands": "HBI",
    "carter's": "CRI",
    "ross stores": "ROST",
    "tjx": "TJX",
    "tj maxx": "TJX",
    "burlington": "BURL",
    "ulta": "ULTA",
    "estee lauder": "EL",
    "church dwight": "CHD",
    "colgate": "CL",
    "procter gamble": "PG",
    "procter & gamble": "PG",
    "pg": "PG",
    "unilever": "UL",
    "kimberly clark": "KMB",
    "clorox": "CLX",
    "henkel": "HENKY",
    "reckitt": "RBGLY",

    # ── Food & Beverage ───────────────────────────────────────────────────────
    "mcdonalds": "MCD",
    "mcdonald's": "MCD",
    "starbucks": "SBUX",
    "chipotle": "CMG",
    "yum brands": "YUM",
    "yum!": "YUM",
    "restaurant brands": "QSR",
    "dominos": "DPZ",
    "domino's": "DPZ",
    "papa johns": "PZZA",
    "wingstop": "WING",
    "shake shack": "SHAK",
    "darden": "DRI",
    "olive garden": "DRI",
    "texas roadhouse": "TXRH",
    "cracker barrel": "CBRL",
    "dunkin": "DNKN",
    "coca cola": "KO",
    "coke": "KO",
    "pepsi": "PEP",
    "pepsico": "PEP",
    "monster": "MNST",
    "monster beverage": "MNST",
    "redbull": "RDBLY",
    "constellation brands": "STZ",
    "anheuser busch": "BUD",
    "budweiser": "BUD",
    "heineken": "HEINY",
    "molson coors": "TAP",
    "boston beer": "SAM",
    "kraft heinz": "KHC",
    "general mills": "GIS",
    "kellanova": "K",
    "kelloggs": "K",
    "kellogg's": "K",
    "campbell soup": "CPB",
    "hershey": "HSY",
    "mondelez": "MDLZ",
    "mars": "MMMB",
    "tyson foods": "TSN",
    "hormel": "HRL",
    "sysco": "SYY",
    "us foods": "USFD",
    "fresh del monte": "FDP",

    # ── Energy ────────────────────────────────────────────────────────────────
    "exxon": "XOM",
    "exxonmobil": "XOM",
    "chevron": "CVX",
    "conocophillips": "COP",
    "shell": "SHEL",
    "bp": "BP",
    "totalenergies": "TTE",
    "schlumberger": "SLB",
    "slb": "SLB",
    "halliburton": "HAL",
    "baker hughes": "BKR",
    "pioneer natural": "PXD",
    "devon energy": "DVN",
    "eog resources": "EOG",
    "coterra": "CTRA",
    "marathon oil": "MRO",
    "hess": "HES",
    "occidental": "OXY",
    "valero": "VLO",
    "phillips 66": "PSX",
    "marathon petroleum": "MPC",
    "williams companies": "WMB",
    "kinder morgan": "KMI",
    "oneok": "OKE",
    "nextera": "NEE",
    "nextera energy": "NEE",
    "duke energy": "DUK",
    "southern company": "SO",
    "dominion": "D",
    "american electric power": "AEP",
    "aep": "AEP",
    "exelon": "EXC",
    "pge": "PCG",
    "pg&e": "PCG",
    "firstenergy": "FE",
    "entergy": "ETR",

    # ── Industrials / Aerospace / Defense ─────────────────────────────────────
    "boeing": "BA",
    "lockheed martin": "LMT",
    "lockheed": "LMT",
    "raytheon": "RTX",
    "rtx": "RTX",
    "northrop grumman": "NOC",
    "northrop": "NOC",
    "general dynamics": "GD",
    "l3harris": "LHX",
    "textron": "TXT",
    "general electric": "GE",
    "ge": "GE",
    "honeywell": "HON",
    "3m": "MMM",
    "illinois tool works": "ITW",
    "itw": "ITW",
    "emerson electric": "EMR",
    "parker hannifin": "PH",
    "eaton": "ETN",
    "rockwell automation": "ROK",
    "fortive": "FTV",
    "roper technologies": "ROP",
    "ametek": "AME",
    "xylem": "XYL",
    "watts water": "WTS",
    "nordson": "NDSN",
    "graco": "GGG",
    "dover": "DOV",
    "pentair": "PNR",
    "rexnord": "RXN",
    "caterpillar": "CAT",
    "deere": "DE",
    "john deere": "DE",
    "cnh industrial": "CNHI",
    "agco": "AGCO",
    "terex": "TEX",
    "oshkosh": "OSK",
    "paccar": "PCAR",
    "navistar": "NAV",
    "cummins": "CMI",
    "wabtec": "WAB",
    "westinghouse": "WEC",
    "ups": "UPS",
    "fedex": "FDX",
    "dhl": "DPSGY",
    "xpo": "XPO",
    "jb hunt": "JBHT",
    "old dominion": "ODFL",
    "werner": "WERN",
    "knight swift": "KNX",

    # ── Auto ──────────────────────────────────────────────────────────────────
    "general motors": "GM",
    "gm": "GM",
    "ford": "F",
    "stellantis": "STLA",
    "chrysler": "STLA",
    "rivian": "RIVN",
    "lucid": "LCID",
    "fisker": "FSR",
    "nio": "NIO",
    "li auto": "LI",
    "xpeng": "XPEV",
    "byd": "BYDDY",
    "toyota": "TM",
    "honda": "HMC",
    "subaru": "FUJHY",
    "mazda": "MZDAY",
    "nissan": "NSANY",
    "volkswagen": "VWAGY",
    "vw": "VWAGY",
    "bmw": "BMWYY",
    "mercedes": "MBGYY",
    "ferrari": "RACE",
    "porsche": "POAHY",
    "lamborghini": "VWAGY",
    "volvo": "VLVLY",

    # ── Real Estate / REITs ───────────────────────────────────────────────────
    "american tower": "AMT",
    "crown castle": "CCI",
    "sbac": "SBAC",
    "prologis": "PLD",
    "simon property": "SPG",
    "realty income": "O",
    "vici properties": "VICI",
    "welltower": "WELL",
    "ventas": "VTR",
    "equinix": "EQIX",
    "digital realty": "DLR",
    "iron mountain": "IRM",
    "public storage": "PSA",
    "extra space": "EXR",
    "camden property": "CPT",
    "mid america": "MAA",
    "avalonbay": "AVB",
    "equity residential": "EQR",
    "sun communities": "SUI",

    # ── Materials / Mining ────────────────────────────────────────────────────
    "newmont": "NEM",
    "barrick": "GOLD",
    "barrick gold": "GOLD",
    "freeport mcmoran": "FCX",
    "freeport": "FCX",
    "rio tinto": "RIO",
    "bhp": "BHP",
    "vale": "VALE",
    "alcoa": "AA",
    "nucor": "NUE",
    "steel dynamics": "STLD",
    "us steel": "X",
    "cleveland cliffs": "CLF",
    "dow": "DOW",
    "dupont": "DD",
    "basf": "BASFY",
    "lyondellbasell": "LYB",
    "eastman chemical": "EMN",
    "westrock": "WRK",
    "international paper": "IP",
    "packaging corp": "PKG",

    # ── Crypto-adjacent ───────────────────────────────────────────────────────
    "coinbase": "COIN",
    "microstrategy": "MSTR",
    "marathon digital": "MARA",
    "riot platforms": "RIOT",
    "riot": "RIOT",
    "cleanspark": "CLSK",
    "core scientific": "CORZ",

    # ── ETFs / Indices ────────────────────────────────────────────────────────
    "spy": "SPY",
    "s&p 500": "SPY",
    "s&p": "SPY",
    "qqq": "QQQ",
    "nasdaq etf": "QQQ",
    "dow jones": "DIA",
    "dia": "DIA",
    "iwm": "IWM",
    "russell 2000": "IWM",
    "vti": "VTI",
    "ark": "ARKK",
    "ark innovation": "ARKK",
}

# Build a reverse map: ticker → canonical ticker (handles bare ticker input)
TICKER_SET = set(COMPANY_NAME_TO_TICKER.values())


def resolve_tickers(text: str, exclude: set[str]) -> list[str]:
    """
    Extract ticker symbols from text using two strategies:
    1. Direct ticker symbols ($AAPL or bare AAPL)
    2. Company name matching with word boundaries (e.g. "nvidia" → "NVDA")
    Returns up to 3 unique tickers.
    """
    lower = text.lower()
    found: list[str] = []
    seen: set[str] = set()

    # Strategy 1: $TICKER (highest confidence) then bare uppercase words
    for t in re.findall(r'\$([A-Za-z]{1,5})', text) + re.findall(r'\b([A-Z]{2,5})\b', text):
        t = t.upper()
        if t not in exclude and t not in seen:
            seen.add(t)
            found.append(t)

    # Strategy 2: company name lookup using word boundaries to avoid substring false-positives
    for name, ticker in COMPANY_NAME_TO_TICKER.items():
        pattern = r'\b' + re.escape(name) + r'\b'
        if re.search(pattern, lower) and ticker not in seen:
            seen.add(ticker)
            found.append(ticker)

    return found[:3]
