import { normalizeLocale } from "@/lib/locale";

type CopySections = {
  header: {
    poweredByGemini: string;
    language: string;
    signOut: string;
    logIn: string;
    signUp: string;
  };
  sidebar: {
    menu: string;
    dashboard: string;
    dashboardDesc: string;
    addStocks: string;
    addStocksDesc: string;
    newsFeed: string;
    newsFeedDesc: string;
    aiChat: string;
    aiChatDesc: string;
    voiceNews: string;
    voiceNewsDesc: string;
    settings: string;
  };
  dashboard: {
    startTracking: string;
    startTrackingDesc: string;
    addFirstStock: string;
    aiSummary: string;
    loading: string;
    live: string;
    loadingData: string;
    trackedStocks: string;
  };
  dashboardLayout: {
    addStocksTitle: string;
    addStocksDesc: string;
    newsFeedTitle: string;
    newsFeedDesc: string;
    aiChatTitle: string;
    aiChatDesc: string;
    voiceNewsTitle: string;
    voiceNewsDesc: string;
    sentimentAnalysis: string;
    askArticle: string;
  };
  landing: {
    systemOnline: string;
    login: string;
    getStarted: string;
    analyticsActive: string;
    marketTerminal: string;
    heroLine1: string;
    heroLine2: string;
    heroSub1: string;
    heroSub2: string;
    startTrading: string;
    signIn: string;
    analytics: string;
    smartDataEngine: string;
    smartDataEngineDesc: string;
    aiAssistant: string;
    wealthVisorAi: string;
    wealthVisorAiDesc: string;
    probabilities: string;
    marketConfidence: string;
    marketConfidenceDesc: string;
    systemStatus: string;
    systemReady: string;
  };
  auth: {
    welcomeBack: string;
    loginSubtitle: string;
    emailAddress: string;
    password: string;
    forgotPassword: string;
    authenticating: string;
    signIn: string;
    noAccount: string;
    signUp: string;
    createAccount: string;
    signupSubtitle: string;
    fullName: string;
    creatingAccount: string;
    alreadyHaveAccount: string;
    logIn: string;
    checkEmail: string;
    confirmationLine1: string;
    confirmationLine2: string;
    important: string;
    spamHint: string;
    goToLogin: string;
    accountExists: string;
    loginErrorFallback: string;
    signupErrorFallback: string;
    loadingPortfolio: string;
    addStockFailed: string;
    removeStockFailed: string;
  };
  voiceNews: {
    generating: string;
    pause: string;
    resume: string;
    play: string;
    theScoop: string;
    stop: string;
    generateNew: string;
    transcript: string;
  };
};

const enUS: CopySections = {
  header: {
    poweredByGemini: "Powered by Gemini",
    language: "Language",
    signOut: "Sign out",
    logIn: "Log In",
    signUp: "Sign Up",
  },
  sidebar: {
    menu: "Menu",
    dashboard: "Dashboard",
    dashboardDesc: "Overview & Analytics",
    addStocks: "Add Stocks",
    addStocksDesc: "Track New Stocks",
    newsFeed: "News Feed",
    newsFeedDesc: "Market News",
    aiChat: "AI Chat",
    aiChatDesc: "WealthVisor AI",
    voiceNews: "Voice News",
    voiceNewsDesc: "Audio Commentary",
    settings: "Settings",
  },
  dashboard: {
    startTracking: "START TRACKING",
    startTrackingDesc: "Add stocks to start tracking events and news",
    addFirstStock: "ADD YOUR FIRST STOCK",
    aiSummary: "AI SUMMARY",
    loading: "LOADING",
    live: "LIVE",
    loadingData: "Loading data...",
    trackedStocks: "TRACKED STOCKS",
  },
  dashboardLayout: {
    addStocksTitle: "ADD STOCKS",
    addStocksDesc: "Search and add stocks to your tracking portfolio",
    newsFeedTitle: "NEWS FEED",
    newsFeedDesc: "Latest market news and analysis for your tracked stocks",
    aiChatTitle: "AI CHAT",
    aiChatDesc: "Chat with WealthVisor AI for market insights",
    voiceNewsTitle: "VOICE NEWS",
    voiceNewsDesc: "Listen to AI-generated market commentary",
    sentimentAnalysis: "AI Sentiment Analysis",
    askArticle: "Ask about this article...",
  },
  landing: {
    systemOnline: "SYSTEM: ONLINE",
    login: "[LOGIN]",
    getStarted: "> GET STARTED",
    analyticsActive: "REAL-TIME ANALYTICS ACTIVE",
    marketTerminal: "MARKET INTELLIGENCE TERMINAL  v2.026",
    heroLine1: "Smart Trading,",
    heroLine2: "Made Simple",
    heroSub1: "Professional-grade market analytics designed for everyday investors.",
    heroSub2: "Real-time insights, AI-powered analysis, no complexity.",
    startTrading: ">> Start Trading",
    signIn: "> Sign In",
    analytics: "ANALYTICS",
    smartDataEngine: "> Smart Data Engine",
    smartDataEngineDesc: "Powerful analytics that synthesize news sentiment, price trends, and market consensus into clear, actionable insights.",
    aiAssistant: "AI ASSISTANT",
    wealthVisorAi: "> WealthVisor AI",
    wealthVisorAiDesc: "Your personal AI advisor that explains complex market data in plain English, helping you make informed investment decisions.",
    probabilities: "PROBABILITIES",
    marketConfidence: "> Market Confidence",
    marketConfidenceDesc: "Clear bull/bear probability scores and sentiment analysis to help you understand market direction and manage risk effectively.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ ready_",
  },
  auth: {
    welcomeBack: "Welcome back",
    loginSubtitle: "Access your Toro portfolio and AI-driven insights.",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot password?",
    authenticating: "Authenticating...",
    signIn: "Sign In",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    createAccount: "Create an account",
    signupSubtitle: "Join Toro to elevate your personal wealth management.",
    fullName: "Full Name",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    logIn: "Log in",
    checkEmail: "Check your email",
    confirmationLine1: "We've sent a confirmation email to",
    confirmationLine2: "Please click the link in the email to verify your account.",
    important: "Important",
    spamHint: "Check your spam folder if you don't see the email within a few minutes.",
    goToLogin: "Go to Login",
    accountExists: "An account with this email already exists. Please log in.",
    loginErrorFallback: "An error occurred during login",
    signupErrorFallback: "An error occurred during signup",
    loadingPortfolio: "Loading your portfolio...",
    addStockFailed: "Failed to add stock. Please try again.",
    removeStockFailed: "Failed to remove stock. Please try again.",
  },
  voiceNews: {
    generating: "Generating...",
    pause: "Pause",
    resume: "Resume",
    play: "Play",
    theScoop: "The Scoop",
    stop: "Stop",
    generateNew: "Generate New",
    transcript: "Transcript",
  },
};

const es: Partial<CopySections> = {
  header: {
    poweredByGemini: "Impulsado por Gemini",
    language: "Idioma",
    signOut: "Cerrar sesion",
    logIn: "Iniciar sesion",
    signUp: "Crear cuenta",
  },
  sidebar: {
    menu: "Menu",
    dashboard: "Panel",
    dashboardDesc: "Resumen y analisis",
    addStocks: "Agregar acciones",
    addStocksDesc: "Seguir nuevas acciones",
    newsFeed: "Noticias",
    newsFeedDesc: "Noticias del mercado",
    aiChat: "Chat IA",
    aiChatDesc: "WealthVisor IA",
    voiceNews: "Noticias por voz",
    voiceNewsDesc: "Comentario en audio",
    settings: "Configuracion",
  },
  dashboard: {
    startTracking: "COMENZAR SEGUIMIENTO",
    startTrackingDesc: "Agrega acciones para seguir eventos y noticias",
    addFirstStock: "AGREGA TU PRIMERA ACCION",
    aiSummary: "RESUMEN IA",
    loading: "CARGANDO",
    live: "EN VIVO",
    loadingData: "Cargando datos...",
    trackedStocks: "ACCIONES SEGUIDAS",
  },
  dashboardLayout: {
    addStocksTitle: "AGREGAR ACCIONES",
    addStocksDesc: "Busca y agrega acciones a tu cartera de seguimiento",
    newsFeedTitle: "NOTICIAS",
    newsFeedDesc: "Ultimas noticias y analisis para tus acciones",
    aiChatTitle: "CHAT IA",
    aiChatDesc: "Habla con WealthVisor IA para informacion del mercado",
    voiceNewsTitle: "NOTICIAS POR VOZ",
    voiceNewsDesc: "Escucha comentarios de mercado generados por IA",
    sentimentAnalysis: "Analisis de sentimiento IA",
    askArticle: "Pregunta sobre este articulo...",
  },
  landing: {
    systemOnline: "SISTEMA: EN LINEA",
    login: "[INICIAR SESION]",
    getStarted: "> COMENZAR",
    analyticsActive: "ANALITICA EN TIEMPO REAL ACTIVA",
    marketTerminal: "TERMINAL DE INTELIGENCIA DE MERCADO  v2.026",
    heroLine1: "Trading inteligente,",
    heroLine2: "hecho simple",
    heroSub1: "Analitica de mercado profesional para inversores cotidianos.",
    heroSub2: "Informacion en tiempo real, analisis con IA, sin complejidad.",
    startTrading: ">> Empezar a invertir",
    signIn: "> Iniciar sesion",
    analytics: "ANALITICA",
    smartDataEngine: "> Motor de datos inteligente",
    smartDataEngineDesc: "Analitica potente que combina sentimiento de noticias, tendencias de precio y consenso de mercado en informacion clara.",
    aiAssistant: "ASISTENTE IA",
    wealthVisorAi: "> WealthVisor IA",
    wealthVisorAiDesc: "Tu asesor personal de IA que explica datos complejos del mercado en lenguaje claro.",
    probabilities: "PROBABILIDADES",
    marketConfidence: "> Confianza del mercado",
    marketConfidenceDesc: "Puntuaciones claras alcista/bajista para entender direccion y riesgo del mercado.",
    systemStatus: "$ estado_sistema: operativo | mercado: en vivo | latencia: <10ms",
    systemReady: "█ listo_",
  },
  auth: {
    welcomeBack: "Bienvenido de nuevo",
    loginSubtitle: "Accede a tu cartera Toro y a analisis impulsado por IA.",
    emailAddress: "Correo electronico",
    password: "Contrasena",
    forgotPassword: "Olvidaste tu contrasena?",
    authenticating: "Autenticando...",
    signIn: "Iniciar sesion",
    noAccount: "No tienes una cuenta?",
    signUp: "Registrate",
    createAccount: "Crear una cuenta",
    signupSubtitle: "Unete a Toro para mejorar tu gestion financiera personal.",
    fullName: "Nombre completo",
    creatingAccount: "Creando cuenta...",
    alreadyHaveAccount: "Ya tienes una cuenta?",
    logIn: "Iniciar sesion",
    checkEmail: "Revisa tu correo",
    confirmationLine1: "Enviamos un correo de confirmacion a",
    confirmationLine2: "Haz clic en el enlace para verificar tu cuenta.",
    important: "Importante",
    spamHint: "Revisa la carpeta de spam si no ves el correo en unos minutos.",
    goToLogin: "Ir a iniciar sesion",
    accountExists: "Ya existe una cuenta con este correo. Inicia sesion.",
    loginErrorFallback: "Ocurrio un error durante el inicio de sesion",
    signupErrorFallback: "Ocurrio un error durante el registro",
    loadingPortfolio: "Cargando tu cartera...",
    addStockFailed: "No se pudo agregar la accion. Intentalo de nuevo.",
    removeStockFailed: "No se pudo eliminar la accion. Intentalo de nuevo.",
  },
  voiceNews: {
    generating: "Generando...",
    pause: "Pausar",
    resume: "Reanudar",
    play: "Reproducir",
    theScoop: "El Resumen",
    stop: "Detener",
    generateNew: "Generar nuevo",
    transcript: "Transcripcion",
  },
};

const hi: Partial<CopySections> = {
  header: {
    poweredByGemini: "Gemini dvara sanchalit",
    language: "Bhasha",
    signOut: "Sign out",
    logIn: "Log in",
    signUp: "Sign up",
  },
  sidebar: {
    menu: "Menu",
    dashboard: "Dashboard",
    dashboardDesc: "Overview aur analytics",
    addStocks: "Stocks joden",
    addStocksDesc: "Naye stocks track karein",
    newsFeed: "News feed",
    newsFeedDesc: "Market khabrein",
    aiChat: "AI chat",
    aiChatDesc: "WealthVisor AI",
    voiceNews: "Voice news",
    voiceNewsDesc: "Audio commentary",
    settings: "Settings",
  },
  dashboard: {
    startTracking: "TRACKING SHURU KAREIN",
    startTrackingDesc: "Events aur news track karne ke liye stocks joden",
    addFirstStock: "APNA PEHLA STOCK JODEN",
    aiSummary: "AI SUMMARY",
    loading: "LOADING",
    live: "LIVE",
    loadingData: "Data load ho raha hai...",
    trackedStocks: "TRACKED STOCKS",
  },
  dashboardLayout: {
    addStocksTitle: "ADD STOCKS",
    addStocksDesc: "Apne tracking portfolio mein stocks search karke joden",
    newsFeedTitle: "NEWS FEED",
    newsFeedDesc: "Aapke tracked stocks ke liye taza market news aur analysis",
    aiChatTitle: "AI CHAT",
    aiChatDesc: "Market insights ke liye WealthVisor AI se baat karein",
    voiceNewsTitle: "VOICE NEWS",
    voiceNewsDesc: "AI-generated market commentary sunein",
    sentimentAnalysis: "AI sentiment analysis",
    askArticle: "Is article ke bare mein puchhein...",
  },
  landing: {
    systemOnline: "SYSTEM: ONLINE",
    login: "[LOG IN]",
    getStarted: "> GET STARTED",
    analyticsActive: "REAL-TIME ANALYTICS ACTIVE",
    marketTerminal: "MARKET INTELLIGENCE TERMINAL  v2.026",
    heroLine1: "Smart trading,",
    heroLine2: "made simple",
    heroSub1: "Rozmarra investors ke liye professional-grade market analytics.",
    heroSub2: "Real-time insights, AI analysis, bina complexity.",
    startTrading: ">> Trading shuru karein",
    signIn: "> Sign in",
    analytics: "ANALYTICS",
    smartDataEngine: "> Smart data engine",
    smartDataEngineDesc: "News sentiment, price trends aur market consensus ko clear insights mein badalne wala analytics engine.",
    aiAssistant: "AI ASSISTANT",
    wealthVisorAi: "> WealthVisor AI",
    wealthVisorAiDesc: "Aapka personal AI advisor jo complex market data ko simple language mein samjhata hai.",
    probabilities: "PROBABILITIES",
    marketConfidence: "> Market confidence",
    marketConfidenceDesc: "Clear bull/bear probability scores se market direction aur risk samjhein.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ ready_",
  },
  auth: {
    welcomeBack: "Wapas swagat hai",
    loginSubtitle: "Apne Toro portfolio aur AI-driven insights tak pahunch payen.",
    emailAddress: "Email address",
    password: "Password",
    forgotPassword: "Password bhool gaye?",
    authenticating: "Authenticate ho raha hai...",
    signIn: "Sign in",
    noAccount: "Kya aapka account nahi hai?",
    signUp: "Sign up",
    createAccount: "Account banayein",
    signupSubtitle: "Personal wealth management ko behtar banane ke liye Toro join karein.",
    fullName: "Full name",
    creatingAccount: "Account ban raha hai...",
    alreadyHaveAccount: "Kya aapka account pehle se hai?",
    logIn: "Log in",
    checkEmail: "Apna email check karein",
    confirmationLine1: "Humne ek confirmation email bheja hai",
    confirmationLine2: "Account verify karne ke liye email link par click karein.",
    important: "Important",
    spamHint: "Agar kuch minute mein email na mile to spam folder check karein.",
    goToLogin: "Login par jayein",
    accountExists: "Is email se account pehle se maujood hai. Kripya log in karein.",
    loginErrorFallback: "Login ke dauran error aaya",
    signupErrorFallback: "Signup ke dauran error aaya",
    loadingPortfolio: "Aapka portfolio load ho raha hai...",
    addStockFailed: "Stock add nahi hua. Dubara koshish karein.",
    removeStockFailed: "Stock remove nahi hua. Dubara koshish karein.",
  },
  voiceNews: {
    generating: "Generate ho raha hai...",
    pause: "Pause",
    resume: "Resume",
    play: "Play",
    theScoop: "The Scoop",
    stop: "Stop",
    generateNew: "Naya generate karein",
    transcript: "Transcript",
  },
};

const fr: Partial<CopySections> = {
  header: {
    poweredByGemini: "Alimente par Gemini",
    language: "Langue",
    signOut: "Se deconnecter",
    logIn: "Connexion",
    signUp: "Inscription",
  },
  sidebar: {
    menu: "Menu",
    dashboard: "Tableau de bord",
    dashboardDesc: "Vue d'ensemble et analyses",
    addStocks: "Ajouter des actions",
    addStocksDesc: "Suivre de nouvelles actions",
    newsFeed: "Fil d'actualites",
    newsFeedDesc: "Actualites du marche",
    aiChat: "Chat IA",
    aiChatDesc: "WealthVisor IA",
    voiceNews: "Actualites vocales",
    voiceNewsDesc: "Commentaire audio",
    settings: "Parametres",
  },
  dashboard: {
    startTracking: "COMMENCER LE SUIVI",
    startTrackingDesc: "Ajoutez des actions pour suivre les evenements et les actualites",
    addFirstStock: "AJOUTEZ VOTRE PREMIERE ACTION",
    aiSummary: "RESUME IA",
    loading: "CHARGEMENT",
    live: "EN DIRECT",
    loadingData: "Chargement des donnees...",
    trackedStocks: "ACTIONS SUIVIES",
  },
  dashboardLayout: {
    addStocksTitle: "AJOUTER DES ACTIONS",
    addStocksDesc: "Recherchez et ajoutez des actions a votre portefeuille",
    newsFeedTitle: "FIL D'ACTUALITES",
    newsFeedDesc: "Dernieres actualites et analyses pour vos actions suivies",
    aiChatTitle: "CHAT IA",
    aiChatDesc: "Discutez avec WealthVisor IA pour des insights de marche",
    voiceNewsTitle: "ACTUALITES VOCALES",
    voiceNewsDesc: "Ecoutez un commentaire de marche genere par IA",
    sentimentAnalysis: "Analyse de sentiment IA",
    askArticle: "Posez une question sur cet article...",
  },
  landing: {
    systemOnline: "SYSTEME: EN LIGNE",
    login: "[CONNEXION]",
    getStarted: "> COMMENCER",
    analyticsActive: "ANALYTIQUE EN TEMPS REEL ACTIVE",
    marketTerminal: "TERMINAL D'INTELLIGENCE DE MARCHE  v2.026",
    heroLine1: "Trading intelligent,",
    heroLine2: "rendu simple",
    heroSub1: "Analytique de marche de niveau professionnel pour tous les investisseurs.",
    heroSub2: "Insights en temps reel, analyse IA, sans complexite.",
    startTrading: ">> Commencer a trader",
    signIn: "> Se connecter",
    analytics: "ANALYTIQUE",
    smartDataEngine: "> Moteur de donnees intelligent",
    smartDataEngineDesc: "Un moteur d'analyse qui combine sentiment des actualites, tendances de prix et consensus du marche.",
    aiAssistant: "ASSISTANT IA",
    wealthVisorAi: "> WealthVisor IA",
    wealthVisorAiDesc: "Votre conseiller IA personnel qui explique les donnees de marche complexes simplement.",
    probabilities: "PROBABILITES",
    marketConfidence: "> Confiance du marche",
    marketConfidenceDesc: "Scores haussier/baissier clairs pour comprendre la direction et le risque.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ pret_",
  },
  auth: {
    welcomeBack: "Bon retour",
    loginSubtitle: "Accedez a votre portefeuille Toro et a des insights IA.",
    emailAddress: "Adresse e-mail",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublie ?",
    authenticating: "Authentification...",
    signIn: "Connexion",
    noAccount: "Vous n'avez pas de compte ?",
    signUp: "Inscription",
    createAccount: "Creer un compte",
    signupSubtitle: "Rejoignez Toro pour ameliorer votre gestion de patrimoine.",
    fullName: "Nom complet",
    creatingAccount: "Creation du compte...",
    alreadyHaveAccount: "Vous avez deja un compte ?",
    logIn: "Connexion",
    checkEmail: "Verifiez votre e-mail",
    confirmationLine1: "Nous avons envoye un e-mail de confirmation a",
    confirmationLine2: "Veuillez cliquer sur le lien pour verifier votre compte.",
    important: "Important",
    spamHint: "Verifiez le dossier spam si vous ne voyez pas l'e-mail rapidement.",
    goToLogin: "Aller a la connexion",
    accountExists: "Un compte avec cet e-mail existe deja. Veuillez vous connecter.",
    loginErrorFallback: "Une erreur est survenue lors de la connexion",
    signupErrorFallback: "Une erreur est survenue lors de l'inscription",
    loadingPortfolio: "Chargement de votre portefeuille...",
    addStockFailed: "Echec de l'ajout de l'action. Reessayez.",
    removeStockFailed: "Echec de la suppression de l'action. Reessayez.",
  },
  voiceNews: {
    generating: "Generation...",
    pause: "Pause",
    resume: "Reprendre",
    play: "Lecture",
    theScoop: "Le Brief",
    stop: "Arreter",
    generateNew: "Generer a nouveau",
    transcript: "Transcription",
  },
};

const de: Partial<CopySections> = {
  header: {
    poweredByGemini: "Unterstutzt von Gemini",
    language: "Sprache",
    signOut: "Abmelden",
    logIn: "Anmelden",
    signUp: "Registrieren",
  },
  sidebar: {
    menu: "Menü",
    dashboard: "Dashboard",
    dashboardDesc: "Ubersicht und Analysen",
    addStocks: "Aktien hinzufugen",
    addStocksDesc: "Neue Aktien verfolgen",
    newsFeed: "News-Feed",
    newsFeedDesc: "Marktnachrichten",
    aiChat: "KI-Chat",
    aiChatDesc: "WealthVisor KI",
    voiceNews: "Sprachnachrichten",
    voiceNewsDesc: "Audio-Kommentar",
    settings: "Einstellungen",
  },
  dashboard: {
    startTracking: "TRACKING STARTEN",
    startTrackingDesc: "Fugen Sie Aktien hinzu, um Ereignisse und Nachrichten zu verfolgen",
    addFirstStock: "ERSTE AKTIE HINZUFUGEN",
    aiSummary: "KI-ZUSAMMENFASSUNG",
    loading: "LADEN",
    live: "LIVE",
    loadingData: "Daten werden geladen...",
    trackedStocks: "VERFOLGTE AKTIEN",
  },
  dashboardLayout: {
    addStocksTitle: "AKTIEN HINZUFUGEN",
    addStocksDesc: "Suchen und fugen Sie Aktien zu Ihrem Portfolio hinzu",
    newsFeedTitle: "NEWS-FEED",
    newsFeedDesc: "Neueste Marktnachrichten und Analysen fur Ihre Aktien",
    aiChatTitle: "KI-CHAT",
    aiChatDesc: "Chatten Sie mit WealthVisor KI fur Markt-Insights",
    voiceNewsTitle: "SPRACH-NEWS",
    voiceNewsDesc: "Horen Sie KI-generierte Marktkommentare",
    sentimentAnalysis: "KI-Sentimentanalyse",
    askArticle: "Fragen Sie zu diesem Artikel...",
  },
  landing: {
    systemOnline: "SYSTEM: ONLINE",
    login: "[ANMELDEN]",
    getStarted: "> STARTEN",
    analyticsActive: "ECHTZEIT-ANALYSE AKTIV",
    marketTerminal: "MARKTINTELLIGENZ-TERMINAL  v2.026",
    heroLine1: "Smartes Trading,",
    heroLine2: "einfach gemacht",
    heroSub1: "Professionelle Marktanalysen fur alltägliche Anleger.",
    heroSub2: "Echtzeit-Insights, KI-Analyse, ohne Komplexitat.",
    startTrading: ">> Trading starten",
    signIn: "> Anmelden",
    analytics: "ANALYSE",
    smartDataEngine: "> Smarte Daten-Engine",
    smartDataEngineDesc: "Leistungsstarke Analysen, die News-Sentiment, Preis-Trends und Marktkonsens zusammenfuhren.",
    aiAssistant: "KI-ASSISTENT",
    wealthVisorAi: "> WealthVisor KI",
    wealthVisorAiDesc: "Ihr personlicher KI-Berater, der komplexe Marktdaten leicht verstandlich erklart.",
    probabilities: "WAHRSCHEINLICHKEITEN",
    marketConfidence: "> Marktvertrauen",
    marketConfidenceDesc: "Klare Bull/Bear-Werte fur Richtung und Risiko im Markt.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ bereit_",
  },
  auth: {
    welcomeBack: "Willkommen zuruck",
    loginSubtitle: "Zugriff auf Ihr Toro-Portfolio und KI-Insights.",
    emailAddress: "E-Mail-Adresse",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    authenticating: "Authentifizierung...",
    signIn: "Anmelden",
    noAccount: "Noch kein Konto?",
    signUp: "Registrieren",
    createAccount: "Konto erstellen",
    signupSubtitle: "Treten Sie Toro bei und verbessern Sie Ihr Vermogensmanagement.",
    fullName: "Vollstandiger Name",
    creatingAccount: "Konto wird erstellt...",
    alreadyHaveAccount: "Bereits ein Konto?",
    logIn: "Anmelden",
    checkEmail: "Prufen Sie Ihre E-Mail",
    confirmationLine1: "Wir haben eine Bestatigungs-E-Mail gesendet an",
    confirmationLine2: "Klicken Sie auf den Link in der E-Mail, um Ihr Konto zu verifizieren.",
    important: "Wichtig",
    spamHint: "Prufen Sie den Spam-Ordner, falls die E-Mail nicht sichtbar ist.",
    goToLogin: "Zur Anmeldung",
    accountExists: "Ein Konto mit dieser E-Mail existiert bereits. Bitte anmelden.",
    loginErrorFallback: "Beim Anmelden ist ein Fehler aufgetreten",
    signupErrorFallback: "Bei der Registrierung ist ein Fehler aufgetreten",
    loadingPortfolio: "Ihr Portfolio wird geladen...",
    addStockFailed: "Aktie konnte nicht hinzugefugt werden. Bitte erneut versuchen.",
    removeStockFailed: "Aktie konnte nicht entfernt werden. Bitte erneut versuchen.",
  },
  voiceNews: {
    generating: "Wird generiert...",
    pause: "Pause",
    resume: "Fortsetzen",
    play: "Abspielen",
    theScoop: "Der Überblick",
    stop: "Stopp",
    generateNew: "Neu generieren",
    transcript: "Transkript",
  },
};

const ar: Partial<CopySections> = {
  header: {
    poweredByGemini: "مدعوم بواسطة Gemini",
    language: "اللغة",
    signOut: "تسجيل الخروج",
    logIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
  },
  sidebar: {
    menu: "القائمة",
    dashboard: "لوحة التحكم",
    dashboardDesc: "نظرة عامة وتحليلات",
    addStocks: "إضافة أسهم",
    addStocksDesc: "تتبع أسهم جديدة",
    newsFeed: "موجز الأخبار",
    newsFeedDesc: "أخبار السوق",
    aiChat: "دردشة الذكاء الاصطناعي",
    aiChatDesc: "WealthVisor AI",
    voiceNews: "الأخبار الصوتية",
    voiceNewsDesc: "تعليق صوتي",
    settings: "الإعدادات",
  },
  dashboard: {
    startTracking: "ابدأ التتبع",
    startTrackingDesc: "أضف الأسهم لبدء تتبع الأحداث والأخبار",
    addFirstStock: "أضف أول سهم لك",
    aiSummary: "ملخص الذكاء الاصطناعي",
    loading: "جاري التحميل",
    live: "مباشر",
    loadingData: "جاري تحميل البيانات...",
    trackedStocks: "الأسهم المتتبعة",
  },
  dashboardLayout: {
    addStocksTitle: "إضافة أسهم",
    addStocksDesc: "ابحث وأضف الأسهم إلى محفظة التتبع",
    newsFeedTitle: "موجز الأخبار",
    newsFeedDesc: "آخر أخبار السوق والتحليلات لأسهمك",
    aiChatTitle: "دردشة الذكاء الاصطناعي",
    aiChatDesc: "تحدث مع WealthVisor AI للحصول على رؤى السوق",
    voiceNewsTitle: "الأخبار الصوتية",
    voiceNewsDesc: "استمع إلى تعليق السوق المُنشأ بالذكاء الاصطناعي",
    sentimentAnalysis: "تحليل المشاعر بالذكاء الاصطناعي",
    askArticle: "اسأل عن هذا المقال...",
  },
  landing: {
    systemOnline: "النظام: متصل",
    login: "[تسجيل الدخول]",
    getStarted: "> ابدأ الآن",
    analyticsActive: "تحليلات فورية مفعلة",
    marketTerminal: "محطة ذكاء السوق  v2.026",
    heroLine1: "تداول ذكي،",
    heroLine2: "ببساطة",
    heroSub1: "تحليلات سوق احترافية للمستثمرين اليوميين.",
    heroSub2: "رؤى فورية، تحليل بالذكاء الاصطناعي، دون تعقيد.",
    startTrading: ">> ابدأ التداول",
    signIn: "> تسجيل الدخول",
    analytics: "التحليلات",
    smartDataEngine: "> محرك بيانات ذكي",
    smartDataEngineDesc: "تحليلات قوية تجمع مشاعر الأخبار واتجاهات الأسعار وإجماع السوق في رؤى واضحة.",
    aiAssistant: "مساعد الذكاء الاصطناعي",
    wealthVisorAi: "> WealthVisor AI",
    wealthVisorAiDesc: "مستشارك الذكي الشخصي الذي يشرح بيانات السوق المعقدة بلغة بسيطة.",
    probabilities: "الاحتمالات",
    marketConfidence: "> ثقة السوق",
    marketConfidenceDesc: "درجات صعود/هبوط واضحة لفهم اتجاه السوق وإدارة المخاطر.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ جاهز_",
  },
  auth: {
    welcomeBack: "مرحبًا بعودتك",
    loginSubtitle: "ادخل إلى محفظة Toro الخاصة بك ورؤى الذكاء الاصطناعي.",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    authenticating: "جاري التحقق...",
    signIn: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    signUp: "إنشاء حساب",
    createAccount: "إنشاء حساب",
    signupSubtitle: "انضم إلى Toro لتعزيز إدارة ثروتك الشخصية.",
    fullName: "الاسم الكامل",
    creatingAccount: "جاري إنشاء الحساب...",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    logIn: "تسجيل الدخول",
    checkEmail: "تحقق من بريدك الإلكتروني",
    confirmationLine1: "لقد أرسلنا رسالة تأكيد إلى",
    confirmationLine2: "يرجى الضغط على الرابط في البريد لتأكيد حسابك.",
    important: "مهم",
    spamHint: "تحقق من مجلد الرسائل غير المرغوب فيها إذا لم تجد الرسالة.",
    goToLogin: "الذهاب إلى تسجيل الدخول",
    accountExists: "يوجد حساب بالفعل بهذا البريد الإلكتروني. يرجى تسجيل الدخول.",
    loginErrorFallback: "حدث خطأ أثناء تسجيل الدخول",
    signupErrorFallback: "حدث خطأ أثناء إنشاء الحساب",
    loadingPortfolio: "جارٍ تحميل محفظتك...",
    addStockFailed: "فشل إضافة السهم. حاول مرة أخرى.",
    removeStockFailed: "فشل إزالة السهم. حاول مرة أخرى.",
  },
  voiceNews: {
    generating: "جارٍ الإنشاء...",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    play: "تشغيل",
    theScoop: "الموجز",
    stop: "إيقاف",
    generateNew: "إنشاء جديد",
    transcript: "النص",
  },
};

const ptBR: Partial<CopySections> = {
  header: {
    poweredByGemini: "Com tecnologia Gemini",
    language: "Idioma",
    signOut: "Sair",
    logIn: "Entrar",
    signUp: "Cadastrar",
  },
  sidebar: {
    menu: "Menu",
    dashboard: "Painel",
    dashboardDesc: "Visao geral e analises",
    addStocks: "Adicionar acoes",
    addStocksDesc: "Acompanhar novas acoes",
    newsFeed: "Feed de noticias",
    newsFeedDesc: "Noticias do mercado",
    aiChat: "Chat IA",
    aiChatDesc: "WealthVisor IA",
    voiceNews: "Noticias em audio",
    voiceNewsDesc: "Comentario em audio",
    settings: "Configuracoes",
  },
  dashboard: {
    startTracking: "COMECAR A ACOMPANHAR",
    startTrackingDesc: "Adicione acoes para acompanhar eventos e noticias",
    addFirstStock: "ADICIONE SUA PRIMEIRA ACAO",
    aiSummary: "RESUMO IA",
    loading: "CARREGANDO",
    live: "AO VIVO",
    loadingData: "Carregando dados...",
    trackedStocks: "ACOES ACOMPANHADAS",
  },
  dashboardLayout: {
    addStocksTitle: "ADICIONAR ACOES",
    addStocksDesc: "Pesquise e adicione acoes ao seu portfolio",
    newsFeedTitle: "FEED DE NOTICIAS",
    newsFeedDesc: "Ultimas noticias e analises para suas acoes",
    aiChatTitle: "CHAT IA",
    aiChatDesc: "Converse com o WealthVisor IA para insights de mercado",
    voiceNewsTitle: "NOTICIAS EM AUDIO",
    voiceNewsDesc: "Ouça comentarios de mercado gerados por IA",
    sentimentAnalysis: "Analise de sentimento por IA",
    askArticle: "Pergunte sobre este artigo...",
  },
  landing: {
    systemOnline: "SISTEMA: ONLINE",
    login: "[ENTRAR]",
    getStarted: "> COMECAR",
    analyticsActive: "ANALITICA EM TEMPO REAL ATIVA",
    marketTerminal: "TERMINAL DE INTELIGENCIA DE MERCADO  v2.026",
    heroLine1: "Trading inteligente,",
    heroLine2: "feito de forma simples",
    heroSub1: "Analitica de mercado profissional para investidores do dia a dia.",
    heroSub2: "Insights em tempo real, analise com IA, sem complexidade.",
    startTrading: ">> Comecar a investir",
    signIn: "> Entrar",
    analytics: "ANALITICA",
    smartDataEngine: "> Motor de dados inteligente",
    smartDataEngineDesc: "Analises poderosas que unem sentimento de noticias, tendencias de preco e consenso de mercado.",
    aiAssistant: "ASSISTENTE IA",
    wealthVisorAi: "> WealthVisor IA",
    wealthVisorAiDesc: "Seu consultor pessoal de IA para explicar dados complexos do mercado de forma simples.",
    probabilities: "PROBABILIDADES",
    marketConfidence: "> Confianca de mercado",
    marketConfidenceDesc: "Pontuacoes claras de alta/baixa para entender direcao e risco.",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ pronto_",
  },
  auth: {
    welcomeBack: "Bem-vindo de volta",
    loginSubtitle: "Acesse seu portfolio Toro e insights com IA.",
    emailAddress: "Endereco de e-mail",
    password: "Senha",
    forgotPassword: "Esqueceu a senha?",
    authenticating: "Autenticando...",
    signIn: "Entrar",
    noAccount: "Nao tem uma conta?",
    signUp: "Cadastre-se",
    createAccount: "Criar conta",
    signupSubtitle: "Junte-se ao Toro para melhorar sua gestao de patrimonio.",
    fullName: "Nome completo",
    creatingAccount: "Criando conta...",
    alreadyHaveAccount: "Ja tem uma conta?",
    logIn: "Entrar",
    checkEmail: "Verifique seu e-mail",
    confirmationLine1: "Enviamos um e-mail de confirmacao para",
    confirmationLine2: "Clique no link do e-mail para verificar sua conta.",
    important: "Importante",
    spamHint: "Verifique a pasta de spam se nao encontrar o e-mail em alguns minutos.",
    goToLogin: "Ir para login",
    accountExists: "Ja existe uma conta com este e-mail. Faça login.",
    loginErrorFallback: "Ocorreu um erro durante o login",
    signupErrorFallback: "Ocorreu um erro durante o cadastro",
    loadingPortfolio: "Carregando seu portfolio...",
    addStockFailed: "Falha ao adicionar acao. Tente novamente.",
    removeStockFailed: "Falha ao remover acao. Tente novamente.",
  },
  voiceNews: {
    generating: "Gerando...",
    pause: "Pausar",
    resume: "Retomar",
    play: "Reproduzir",
    theScoop: "Resumo",
    stop: "Parar",
    generateNew: "Gerar novo",
    transcript: "Transcricao",
  },
};

const ja: Partial<CopySections> = {
  header: {
    poweredByGemini: "Gemini 搭載",
    language: "言語",
    signOut: "サインアウト",
    logIn: "ログイン",
    signUp: "登録",
  },
  sidebar: {
    menu: "メニュー",
    dashboard: "ダッシュボード",
    dashboardDesc: "概要と分析",
    addStocks: "銘柄を追加",
    addStocksDesc: "新しい銘柄を追跡",
    newsFeed: "ニュースフィード",
    newsFeedDesc: "市場ニュース",
    aiChat: "AI チャット",
    aiChatDesc: "WealthVisor AI",
    voiceNews: "音声ニュース",
    voiceNewsDesc: "音声コメント",
    settings: "設定",
  },
  dashboard: {
    startTracking: "追跡を開始",
    startTrackingDesc: "銘柄を追加してイベントとニュースを追跡します",
    addFirstStock: "最初の銘柄を追加",
    aiSummary: "AI 要約",
    loading: "読み込み中",
    live: "ライブ",
    loadingData: "データを読み込み中...",
    trackedStocks: "追跡中の銘柄",
  },
  dashboardLayout: {
    addStocksTitle: "銘柄を追加",
    addStocksDesc: "銘柄を検索してポートフォリオに追加",
    newsFeedTitle: "ニュースフィード",
    newsFeedDesc: "追跡中の銘柄の最新ニュースと分析",
    aiChatTitle: "AI チャット",
    aiChatDesc: "WealthVisor AI と会話して市場インサイトを取得",
    voiceNewsTitle: "音声ニュース",
    voiceNewsDesc: "AI 生成の市場コメントを聞く",
    sentimentAnalysis: "AI センチメント分析",
    askArticle: "この記事について質問する...",
  },
  landing: {
    systemOnline: "SYSTEM: ONLINE",
    login: "[ログイン]",
    getStarted: "> はじめる",
    analyticsActive: "リアルタイム分析 有効",
    marketTerminal: "マーケットインテリジェンスターミナル  v2.026",
    heroLine1: "スマートトレードを、",
    heroLine2: "もっとシンプルに",
    heroSub1: "日常の投資家向けに設計されたプロ仕様の市場分析。",
    heroSub2: "リアルタイムインサイト、AI 分析、複雑さなし。",
    startTrading: ">> 取引を始める",
    signIn: "> ログイン",
    analytics: "分析",
    smartDataEngine: "> スマートデータエンジン",
    smartDataEngineDesc: "ニュース感情、価格トレンド、市場コンセンサスを統合して明確なインサイトを提供。",
    aiAssistant: "AI アシスタント",
    wealthVisorAi: "> WealthVisor AI",
    wealthVisorAiDesc: "複雑な市場データをわかりやすく説明する、あなた専用の AI アドバイザー。",
    probabilities: "確率",
    marketConfidence: "> 市場信頼度",
    marketConfidenceDesc: "明確なブル/ベア確率で市場方向とリスクを把握。",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ ready_",
  },
  auth: {
    welcomeBack: "おかえりなさい",
    loginSubtitle: "Toro のポートフォリオと AI インサイトにアクセス。",
    emailAddress: "メールアドレス",
    password: "パスワード",
    forgotPassword: "パスワードを忘れましたか？",
    authenticating: "認証中...",
    signIn: "ログイン",
    noAccount: "アカウントをお持ちでないですか？",
    signUp: "登録",
    createAccount: "アカウント作成",
    signupSubtitle: "Toro に参加して資産管理をレベルアップ。",
    fullName: "氏名",
    creatingAccount: "アカウント作成中...",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？",
    logIn: "ログイン",
    checkEmail: "メールを確認してください",
    confirmationLine1: "確認メールを送信しました: ",
    confirmationLine2: "メール内のリンクをクリックしてアカウントを確認してください。",
    important: "重要",
    spamHint: "数分経っても届かない場合は迷惑メールを確認してください。",
    goToLogin: "ログインへ",
    accountExists: "このメールのアカウントは既に存在します。ログインしてください。",
    loginErrorFallback: "ログイン中にエラーが発生しました",
    signupErrorFallback: "登録中にエラーが発生しました",
    loadingPortfolio: "ポートフォリオを読み込み中...",
    addStockFailed: "銘柄の追加に失敗しました。もう一度お試しください。",
    removeStockFailed: "銘柄の削除に失敗しました。もう一度お試しください。",
  },
  voiceNews: {
    generating: "生成中...",
    pause: "一時停止",
    resume: "再開",
    play: "再生",
    theScoop: "ザ・スクープ",
    stop: "停止",
    generateNew: "新規生成",
    transcript: "文字起こし",
  },
};

const zhCN: Partial<CopySections> = {
  header: {
    poweredByGemini: "由 Gemini 提供支持",
    language: "语言",
    signOut: "退出登录",
    logIn: "登录",
    signUp: "注册",
  },
  sidebar: {
    menu: "菜单",
    dashboard: "仪表盘",
    dashboardDesc: "总览与分析",
    addStocks: "添加股票",
    addStocksDesc: "跟踪新股票",
    newsFeed: "新闻流",
    newsFeedDesc: "市场新闻",
    aiChat: "AI 聊天",
    aiChatDesc: "WealthVisor AI",
    voiceNews: "语音新闻",
    voiceNewsDesc: "音频评论",
    settings: "设置",
  },
  dashboard: {
    startTracking: "开始跟踪",
    startTrackingDesc: "添加股票以开始跟踪事件和新闻",
    addFirstStock: "添加第一只股票",
    aiSummary: "AI 摘要",
    loading: "加载中",
    live: "实时",
    loadingData: "正在加载数据...",
    trackedStocks: "已跟踪股票",
  },
  dashboardLayout: {
    addStocksTitle: "添加股票",
    addStocksDesc: "搜索并将股票添加到您的跟踪组合",
    newsFeedTitle: "新闻流",
    newsFeedDesc: "您跟踪股票的最新市场新闻与分析",
    aiChatTitle: "AI 聊天",
    aiChatDesc: "与 WealthVisor AI 对话获取市场洞察",
    voiceNewsTitle: "语音新闻",
    voiceNewsDesc: "收听 AI 生成的市场评论",
    sentimentAnalysis: "AI 情绪分析",
    askArticle: "询问这篇文章...",
  },
  landing: {
    systemOnline: "系统：在线",
    login: "[登录]",
    getStarted: "> 立即开始",
    analyticsActive: "实时分析已启用",
    marketTerminal: "市场智能终端  v2.026",
    heroLine1: "聪明交易，",
    heroLine2: "简单实现",
    heroSub1: "为普通投资者打造的专业级市场分析。",
    heroSub2: "实时洞察、AI 分析、无需复杂操作。",
    startTrading: ">> 开始交易",
    signIn: "> 登录",
    analytics: "分析",
    smartDataEngine: "> 智能数据引擎",
    smartDataEngineDesc: "融合新闻情绪、价格趋势与市场共识，提供清晰可执行的洞察。",
    aiAssistant: "AI 助手",
    wealthVisorAi: "> WealthVisor AI",
    wealthVisorAiDesc: "您的个人 AI 顾问，用通俗语言解释复杂市场数据。",
    probabilities: "概率",
    marketConfidence: "> 市场信心",
    marketConfidenceDesc: "清晰的多空概率评分，帮助理解市场方向并管理风险。",
    systemStatus: "$ system_status: operational | market_feed: live | latency: <10ms",
    systemReady: "█ ready_",
  },
  auth: {
    welcomeBack: "欢迎回来",
    loginSubtitle: "访问您的 Toro 投资组合与 AI 洞察。",
    emailAddress: "邮箱地址",
    password: "密码",
    forgotPassword: "忘记密码？",
    authenticating: "正在验证...",
    signIn: "登录",
    noAccount: "还没有账号？",
    signUp: "注册",
    createAccount: "创建账号",
    signupSubtitle: "加入 Toro，提升您的个人财富管理。",
    fullName: "姓名",
    creatingAccount: "正在创建账号...",
    alreadyHaveAccount: "已有账号？",
    logIn: "登录",
    checkEmail: "请检查您的邮箱",
    confirmationLine1: "我们已向以下地址发送确认邮件：",
    confirmationLine2: "请点击邮件中的链接完成账号验证。",
    important: "重要",
    spamHint: "若几分钟内未收到邮件，请检查垃圾邮件文件夹。",
    goToLogin: "前往登录",
    accountExists: "该邮箱已存在账号，请直接登录。",
    loginErrorFallback: "登录时发生错误",
    signupErrorFallback: "注册时发生错误",
    loadingPortfolio: "正在加载您的投资组合...",
    addStockFailed: "添加股票失败，请重试。",
    removeStockFailed: "移除股票失败，请重试。",
  },
  voiceNews: {
    generating: "生成中...",
    pause: "暂停",
    resume: "继续",
    play: "播放",
    theScoop: "速览",
    stop: "停止",
    generateNew: "重新生成",
    transcript: "文字稿",
  },
};

const localePacks: Record<string, Partial<CopySections>> = {
  es,
  hi,
  fr,
  de,
  ar,
  "pt-BR": ptBR,
  ja,
  "zh-CN": zhCN,
};

function mergeWithEnglish(overrides: Partial<CopySections>): CopySections {
  return {
    header: { ...enUS.header, ...(overrides.header || {}) },
    sidebar: { ...enUS.sidebar, ...(overrides.sidebar || {}) },
    dashboard: { ...enUS.dashboard, ...(overrides.dashboard || {}) },
    dashboardLayout: { ...enUS.dashboardLayout, ...(overrides.dashboardLayout || {}) },
    landing: { ...enUS.landing, ...(overrides.landing || {}) },
    auth: { ...enUS.auth, ...(overrides.auth || {}) },
    voiceNews: { ...enUS.voiceNews, ...(overrides.voiceNews || {}) },
  };
}

export function getUICopy(locale: string): CopySections {
  const normalized = normalizeLocale(locale);
  if (normalized === "en-US") return enUS;
  return mergeWithEnglish(localePacks[normalized] || {});
}
